prefix = "udacity"
rgname = "Azuredevops"
location = "west europe"
username = "vmuser"
password = "Passwordac$mki$89"
vm-count = 2
packer_rg = "Azuredevops"
packer_image_name = "myPackerImage"
project = "DevOps Project 1"